### ISSUE TITLE
How to add MAL API?

### ISSUE THREAD

**Issue by leocordis27** [FuzzyGrim/Yamtrack#131]
Is there a step by step guide to add MyAnimeList API? Let me know if I do the steps correctly.

I already get my API key from MAL.
![image](https://github.com/FuzzyGrim/Yamtrack/assets/111774381/48468a8a-66b1-4d33-9793-ad9f0f184879)

I add the API key to the portainer stack .
![image](https://github.com/FuzzyGrim/Yamtrack/assets/111774381/aed0478e-e3f3-49e4-b242-0ad64f22b187)

I put the API key in the profile setting.
![image](https://github.com/FuzzyGrim/Yamtrack/assets/111774381/eeb80c36-4621-48f8-bd8a-78a03ae5fcb1)

Result is error in imporitng. I also try to put in my MAL username but it also gives error.
![image](https://github.com/FuzzyGrim/Yamtrack/assets/111774381/9ccf4ee2-3903-4029-bbbc-e8bd6a5231f0)

Yamtrack Version: v0.8.3

**Comment by FuzzyGrim** [comment]
I haven't written a step-by-step guide yet.

Make sure you use the Client ID and not the Client Secret. The Client ID just needs to be set as an environment variable with the key "MAL_API", as you have done. You don't need to do anything else in the application UI to add the MAL API. You can check if your API key works by searching for anime or manga.

The MyAnimeList field on the profile page is only for importing your media from MyAnimeList, for that you just need to enter your MyAnimeList username.

If you are still having problems, could you share your logs?

**Comment by leocordis27** [comment]
> I haven't written a step-by-step guide yet.
> 
> Make sure you use the Client ID and not the Client Secret. The Client ID just needs to be set as an environment variable with the key "MAL_API", as you have done. You don't need to do anything else in the application UI to add the MAL API. You can check if your API key works by searching for anime or manga.
> 
> The MyAnimeList field on the profile page is only for importing your media from MyAnimeList, for that you just need to enter your MyAnimeList username.
> 
> If you are still having problems, could you share your logs?

Yes I only have the Client ID and not Client Secret when I get the API from MyAnimeList.
I then add my MAL username in the Yamtrack settings page and get the following page.

![image](https://github.com/FuzzyGrim/Yamtrack/assets/111774381/8b0a4497-6144-4998-ba1d-9858bbf4ded9)

Below is the log from portainer, note that I already added some manga via the Yamtrack UI before trying to connect the MAL username.

[2024-03-26 11:33:28 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:33:28 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:33:36 +0700] [44] [INFO] Darwin's Game saved successfully.
[2024-03-26 11:33:38 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:33:38 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:33:44 +0700] [44] [INFO] Darwin Jihen saved successfully.
[2024-03-26 11:33:46 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:33:46 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:33:55 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:33:55 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:34:04 +0700] [44] [INFO] Game Maou saved successfully.
[2024-03-26 11:34:05 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:34:05 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:34:15 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:34:15 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:34:21 +0700] [44] [INFO] Ichinose-ke no Taizai saved successfully.
[2024-03-26 11:34:23 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:34:23 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:34:30 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:34:30 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:34:37 +0700] [44] [INFO] Kajiki no Ryourinin saved successfully.
[2024-03-26 11:34:40 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:34:40 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:34:51 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:34:51 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:34:57 +0700] [44] [INFO] Pension Life Vampire saved successfully.
[2024-03-26 11:34:59 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:34:59 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:35:05 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:35:05 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:35:10 +0700] [44] [INFO] Vibration Man saved successfully.
[2024-03-26 11:35:12 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:35:12 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:35:20 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:35:20 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:35:26 +0700] [44] [INFO] World Trigger saved successfully.
[2024-03-26 11:35:28 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:35:28 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:35:35 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:35:35 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:35:41 +0700] [44] [INFO] Yotsuba to! saved successfully.
[2024-03-26 11:35:43 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:35:43 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:35:51 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:35:51 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:35:55 +0700] [44] [INFO] Yumeochi: Yume de Bokura wa Koi ni Ochiru saved successfully.
[2024-03-26 11:35:57 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:35:57 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:36:16 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:36:16 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:36:30 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:36:30 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:44:19 +0700] [44] [INFO] One Piece saved successfully.
[2024-03-26 11:44:24 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:44:24 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:44:33 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:44:34 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:45:17 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:45:17 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:45:32 +0700] [44] [INFO] Zom 100: Zombie ni Naru made ni Shitai 100 no Koto saved successfully.
[2024-03-26 11:45:34 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:45:34 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:45:50 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:45:50 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:46:06 +0700] [44] [INFO] Kimi ga Shine: Tasuuketsu Death Game saved successfully.
[2024-03-26 11:46:08 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:46:08 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:49:02 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:49:02 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:49:09 +0700] [44] [INFO] Gokurakugai saved successfully.
[2024-03-26 11:49:11 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:49:11 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:49:16 +0700] [44] [INFO] Jigokuraku saved successfully.
[2024-03-26 11:49:19 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 11:49:19 +0700] [44] [WARNING] Not Found: /graphql
[2024-03-26 23:12:15 +0700] [44] [INFO] Importing animes from MyAnimeList
[2024-03-26 23:12:19 +0700] [44] [INFO] Importing mangas from MyAnimeList
[2024-03-26 23:12:27 +0700] [44] [ERROR] Internal Server Error: /import/mal
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/integrations/views.py", line 30, in wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/integrations/views.py", line 39, in import_mal
    mal.importer(request.POST["mal"], request.user)
  File "/yamtrack/integrations/imports/mal.py", line 21, in importer
    bulk_add_manga = add_media_list(mangas, "manga", user)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/integrations/imports/mal.py", line 55, in add_media_list
    status = get_status(content["list_status"]["status"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/integrations/imports/mal.py", line 97, in get_status
    return switcher[status]
           ~~~~~~~~^^^^^^^^
KeyError: 'plan_to_read'

**Comment by FuzzyGrim** [comment]
Thanks, I think I fixed it in #133, could you try it with the docker image "ghcr.io/fuzzygrim/yamtrack:pr-133"?
