### ISSUE TITLE
cant open any manga/anime page since 4/29/24 morning on dev release

### ISSUE THREAD

**Issue by reitenth** [FuzzyGrim/Yamtrack#154]
Environment:

Request Method: GET
Request URL: http://192.168.68.61:8000/details/manga/107931/blue-period

Django Version: 5.0.4
Python Version: 3.11.9
Installed Applications:
['whitenoise.runserver_nostatic',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'app',
 'users',
 'integrations',
 'crispy_forms',
 'crispy_bootstrap5',
 'debug_toolbar',
 'django_celery_results',
 'simple_history']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'config.middleware.LoginRequiredMiddleware',
 'simple_history.middleware.HistoryRequestMiddleware']

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/app/views.py", line 208, in media_details
    media_metadata = services.get_media_metadata(media_type, media_id)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/app/providers/services.py", line 108, in get_media_metadata
    media_metadata = mal.manga(media_id)
                     ^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/app/providers/mal.py", line 105, in manga
    data = cache.get(f"manga_{media_id}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/cache/backends/redis.py", line 187, in get
    return self._cache.get(key, default)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/cache/backends/redis.py", line 99, in get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/commands/core.py", line 1830, in get
    return self.execute_command("GET", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 540, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 1104, in get_connection
    connection.connect()
    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fakeredis/_server.py", line 84, in connect
    super().connect()
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 288, in connect
    self.on_connect()
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 354, in on_connect
    auth_response = self.read_response()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fakeredis/_server.py", line 126, in read_response
    raise response
    ^^^^^^^^^^^^^^

Exception Type: ResponseError at /details/manga/107931/blue-period
Exception Value: unknown command `auth`, with args beginning with:

**Comment by FuzzyGrim** [comment]
Should be fixed on dev, could you try pulling again?

**Comment by reitenth** [comment]
that fixed it. thanks!
