### ISSUE TITLE
[BUG] [MANGA] Manga added through MangaUpdate can't be edited (call to api.myanimelist.net in the log with a not found error)

### ISSUE THREAD

**Issue by Kazer67** [FuzzyGrim/Yamtrack#229]
There seem to be a little bug with the new MangaUpdate feature, in the edit part it seem there's call toward myanimelist instead of MangeUpdate which lead to a server 500 error (not part of that particular bug but maybe an improvement: it could be useful for users to add a more explicit error message like in that case "MyAnimeList: Not Found Error").

Step to reproduce the bug:

* Add a Manga through the MangaUpdate search, it's added successfully and displayed in the MangeList.
* Go to your manga list and try either to edit directly (with the popup) or access it (by clicking on it), an error 500 will appear.

Here's the error's log:
```
yamtrack        | [2024-09-30 20:56:32 +0000] [26] [INFO] Guiyi Yaoji Shi: Wo De Bingren Jie Wei Kongbu saved successfully.
yamtrack        | [2024-09-30 20:56:46 +0000] [27] [WARNING] Request failed. Retrying in 1 seconds.
yamtrack        | [2024-09-30 20:56:47 +0000] [27] [ERROR] Request failed after retry. Raising error.
yamtrack        | [2024-09-30 20:56:47 +0000] [27] [ERROR] Internal Server Error: /media_save
yamtrack        | Traceback (most recent call last):
yamtrack        |   File "/yamtrack/app/providers/services.py", line 50, in wrapper
yamtrack        |     return func(*args, **kwargs)
yamtrack        |            ^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/yamtrack/app/providers/services.py", line 91, in api_request
yamtrack        |     json_response = request_error_handling(error, *args)
yamtrack        |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/yamtrack/app/providers/services.py", line 157, in request_error_handling
yamtrack        |     raise error  # re-raise the error if it's not handled
yamtrack        |     ^^^^^^^^^^^
yamtrack        |   File "/yamtrack/app/providers/services.py", line 86, in api_request
yamtrack        |     response.raise_for_status()
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
yamtrack        |     raise HTTPError(http_error_msg, response=self)
yamtrack        | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.myanimelist.net/v2/manga/71309113396?fields=title%2Cmain_picture%2Cmedia_type%2Cstart_date%2Cend_date%2Csynopsis%2Cstatus%2Cgenres%2Crecommendations%2Cnum_chapters%2Crelated_manga%2Crecommendations
yamtrack        | 
yamtrack        | During handling of the above exception, another exception occurred:
yamtrack        | 
yamtrack        | Traceback (most recent call last):
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
yamtrack        |     response = get_response(request)
yamtrack        |                ^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
yamtrack        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
yamtrack        |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/http.py", line 64, in inner
yamtrack        |     return func(request, *args, **kwargs)
yamtrack        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/yamtrack/app/views.py", line 217, in media_save
yamtrack        |     form.save()
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/forms/models.py", line 554, in save
yamtrack        |     self.instance.save()
yamtrack        |   File "/yamtrack/app/models.py", line 172, in save
yamtrack        |     self.process_progress()
yamtrack        |   File "/yamtrack/app/models.py", line 184, in process_progress
yamtrack        |     max_progress = services.get_media_metadata(
yamtrack        |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/yamtrack/app/providers/services.py", line 169, in get_media_metadata
yamtrack        |     media_metadata = mal.manga(media_id)
yamtrack        |                      ^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/yamtrack/app/providers/mal.py", line 118, in manga
yamtrack        |     response = services.api_request(
yamtrack        |                ^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/yamtrack/app/providers/services.py", line 56, in wrapper
yamtrack        |     return func(*args, **kwargs)
yamtrack        |            ^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/yamtrack/app/providers/services.py", line 91, in api_request
yamtrack        |     json_response = request_error_handling(error, *args)
yamtrack        |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/yamtrack/app/providers/services.py", line 157, in request_error_handling
yamtrack        |     raise error  # re-raise the error if it's not handled
yamtrack        |     ^^^^^^^^^^^
yamtrack        |   File "/yamtrack/app/providers/services.py", line 86, in api_request
yamtrack        |     response.raise_for_status()
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
yamtrack        |     raise HTTPError(http_error_msg, response=self)
yamtrack        | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.myanimelist.net/v2/manga/71309113396?fields=title%2Cmain_picture%2Cmedia_type%2Cstart_date%2Cend_date%2Csynopsis%2Cstatus%2Cgenres%2Crecommendations%2Cnum_chapters%2Crelated_manga%2Crecommendations

```

**Comment by FuzzyGrim** [comment]
Thanks, should be fixed with the new release.

**Comment by Kazer67** [comment]
Can confirm, it's fixed.
