### ISSUE TITLE
Feature: Simkl csv/api integration

### ISSUE THREAD

**Issue by FuzzyGrim** [FuzzyGrim/Yamtrack#233]
Add integration with Simkl to allow users to import their watch history into Yamtrack

**Comment by PedroBuffon** [comment]
When trying to authenticate it gives out "{"error":"Some required field is missing"}",the url "https://simkl.com/oauth/authorize?client_id=&redirect_uri=https://track.buffon.cloud/import/simkl&response_type=code", logs don`t show anything as this is a simkl side error. Should this be added to "https://simkl.com/settings/developer/add/" as an app?

**Comment by FuzzyGrim** [comment]
> Should this be added to "https://simkl.com/settings/developer/add/" as an app?

Yesterday it required you to provide your own keys, but I've added some defaults, can you try again?

**Comment by PedroBuffon** [comment]
The auth works, but it gives another error when trying to import shows/movies:
```
[2024-10-13 20:56:14 +0000] [18] [INFO] Task Import from SIMKL[76b05804-1d01-4c5d-a214-a6d2badc3a46] received
[2024-10-13 20:56:15 +0000] [22] [INFO] Processing tv shows
[2024-10-13 20:56:15 +0000] [22] [ERROR] Task Import from SIMKL[76b05804-1d01-4c5d-a214-a6d2badc3a46] raised unexpected: KeyError('seasons')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/integrations/tasks.py", line 33, in import_simkl
    num_tv_imported, num_movie_imported, num_anime_imported, msg = simkl.importer(
                                                                   ^^^^^^^^^^^^^^^
  File "/yamtrack/integrations/imports/simkl.py", line 65, in importer
    tv_count = process_tv_list(data["shows"], user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/integrations/imports/simkl.py", line 82, in process_tv_list
    season_numbers = [season["number"] for season in tv["seasons"]]
                                                     ~~^^^^^^^^^^^
KeyError: 'seasons'
```

**Comment by FuzzyGrim** [comment]
Thanks, could you add `DEBUG=True` in your docker-compose.yml environment variables? Also, I have made some changes so a `docker compose pull` would also be useful.

**Comment by PedroBuffon** [comment]
With the new image and debug mode on:
```
[2024-10-13 21:50:10 +0000] [18] [INFO] Task Import from SIMKL[52baa932-0dea-4e5c-952e-cfbf29df9628] received
[2024-10-13 21:50:10 +0000] [18] [DEBUG] TaskPool: Apply <function fast_trace_task at 0x73a9ab85a980> (args:('Import from SIMKL', '52baa932-0dea-4e5c-952e-cfbf29df9628', {'lang': 'py', 'task': 'Import from SIMKL', 'id': '52baa932-0dea-4e5c-952e-cfbf29df9628', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '52baa932-0dea-4e5c-952e-cfbf29df9628', 'parent_id': None, 'argsrepr': "('track.buffon.cloud', 'https', '910452758aec94e3f1bebaaee8821856527d9ae16149fcd0873cfd88f478eeb1', <SimpleLazyObject: <User: pedrobuffon>>)", 'kwargsrepr': '{}', 'origin': 'gen20@f1bb192fed9f', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}, 'properties': {'correlation_id': '52baa932-0dea-4e5c-952e-cfbf29df9628', 'reply_to': '1f222896-5804-3bf4-93a6-3279220c315a', 'delivery_mode': 2, 'delivery_info': {'exchange': '', 'routing_key': 'celery'}, 'priority': 0, 'body_encoding': 'base64', 'delivery_tag': 'a7791a02-45b3-4a72-934b-340debbf0053'}, 'reply_to': '1f222896-5804-3bf4-93a6-3279220c315a', 'correlation_id':... kwargs:{})
[2024-10-13 21:50:10 +0000] [22] [DEBUG] Starting new HTTPS connection (1): api.simkl.com:443
[2024-10-13 21:50:10 +0000] [22] [DEBUG] https://api.simkl.com:443 "POST /oauth/token HTTP/11" 200 None
[2024-10-13 21:50:10 +0000] [22] [DEBUG] https://api.simkl.com:443 "GET /sync/all-items/?extended=full&episode_watched_at=yes HTTP/11" 200 None
[2024-10-13 21:50:11 +0000] [22] [INFO] Processing tv shows
[2024-10-13 21:50:11 +0000] [22] [DEBUG] Processing My Wife and Kids
[2024-10-13 21:50:11 +0000] [22] [DEBUG] {'last_watched_at': '2017-01-11T21:00:59Z', 'status': 'completed', 'user_rating': None, 'last_watched': 'S05E26', 'next_to_watch': None, 'watched_episodes_count': 123, 'total_episodes_count': 124, 'not_aired_episodes_count': 0, 'show': {'title': 'My Wife and Kids', 'poster': '69/69304434c4411340', 'year': 2001, 'ids': {'simkl': 3, 'slug': 'my-wife-and-kids', 'imdb': 'tt0273855', 'zap2it': 'EP00425822', 'tvdbslug': 'my-wife-and-kids', 'tmdb': '2692', 'traktslug': 'my-wife-and-kids', 'tvdb': '70329'}}}
[2024-10-13 21:50:11 +0000] [22] [ERROR] Task Import from SIMKL[52baa932-0dea-4e5c-952e-cfbf29df9628] raised unexpected: KeyError('seasons')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/integrations/tasks.py", line 33, in import_simkl
    num_tv_imported, num_movie_imported, num_anime_imported, msg = simkl.importer(
                                                                   ^^^^^^^^^^^^^^^
  File "/yamtrack/integrations/imports/simkl.py", line 65, in importer
    tv_count = process_tv_list(data["shows"], user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/integrations/imports/simkl.py", line 83, in process_tv_list
    season_numbers = [season["number"] for season in tv["seasons"]]
                                                     ~~^^^^^^^^^^^
KeyError: 'seasons'
```

**Comment by FuzzyGrim** [comment]
Okay, from my SIMKL test account, when getting TV programs it returns something like:

```
    {
      "last_watched_at": "2024-10-13T22:26:53Z",
      "status": "watching",
      "user_rating": null,
      "last_watched": "S01E03",
      "next_to_watch": "S01E04",
      "watched_episodes_count": 3,
      "total_episodes_count": 124,
      "not_aired_episodes_count": 0,
      "show": {
        "title": "My Wife and Kids",
        "poster": "69\/69304434c4411340",
        "year": 2001,
        "ids": {
          "simkl": 3,
          "slug": "my-wife-and-kids",
          "imdb": "tt0273855",
          "zap2it": "EP00425822",
          "tvdbslug": "my-wife-and-kids",
          "tmdb": "2692",
          "traktslug": "my-wife-and-kids",
          "tvdb": "70329"
        }
      },
      "seasons": [
        {
          "number": 1,
          "episodes": [
            {
              "number": 1,
              "watched_at": "2024-10-13T22:26:52Z"
            },
            {
              "number": 2,
              "watched_at": "2024-10-13T22:26:52Z"
            },
            {
              "number": 3,
              "watched_at": "2024-10-13T22:26:53Z"
            }
          ]
        }
      ]
    }
```

while in your case the watched episodes are missing:

```
{
    "last_watched_at": "2017-01-11T21:00:59Z",
    "status": "completed",
    "user_rating": None,
    "last_watched": "S05E26",
    "next_to_watch": None,
    "watched_episodes_count": 123,
    "total_episodes_count": 124,
    "not_aired_episodes_count": 0,
    "show": {
        "title": "My Wife and Kids",
        "poster": "69/69304434c4411340",
        "year": 2001,
        "ids": {
            "simkl": 3,
            "slug": "my-wife-and-kids",
            "imdb": "tt0273855",
            "zap2it": "EP00425822",
            "tvdbslug": "my-wife-and-kids",
            "tmdb": "2692",
            "traktslug": "my-wife-and-kids",
            "tvdb": "70329",
        },
    },
}
```

Since your entry was from 2017, it may be because there was an update or something. I have added a handler to ignore entries without that data, if the task finishes successfully, you will be able to see how many there are on the task results view.

**Comment by PedroBuffon** [comment]
Okay, i tried with the new update, the tv shows and movies have been imported with some errors:
Not all tv shows and movies have been imported sadly. maybe those with errors didn`t.
```
[2024-10-13 22:54:52 +0000] [22] [ERROR] Request failed after retry. Raising error.
[2024-10-13 22:54:52 +0000] [22] [ERROR] Task Import from SIMKL[bf264c77-7d3d-40a8-99b2-073161220d9d] raised unexpected: HTTPError('404 Client Error: Not Found for url: https://api.themoviedb.org/3/movie/418363?api_key=61572be02f0a068658828f6396aacf60&language=en&append_to_response=recommendations')
Traceback (most recent call last):
  File "/yamtrack/app/providers/services.py", line 54, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/app/providers/services.py", line 95, in api_request
    json_response = request_error_handling(error, *args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/app/providers/services.py", line 161, in request_error_handling
    raise error  # re-raise the error if it's not handled
    ^^^^^^^^^^^
  File "/yamtrack/app/providers/services.py", line 90, in api_request
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.themoviedb.org/3/movie/418363?api_key=61572be02f0a068658828f6396aacf60&language=en&append_to_response=recommendations

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/integrations/tasks.py", line 33, in import_simkl
    num_tv_imported, num_movie_imported, num_anime_imported, msg = simkl.importer(
                                                                   ^^^^^^^^^^^^^^^
  File "/yamtrack/integrations/imports/simkl.py", line 66, in importer
    movie_count = process_movie_list(data["movies"], user)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/integrations/imports/simkl.py", line 189, in process_movie_list
    metadata = app.providers.tmdb.movie(tmdb_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/app/providers/tmdb.py", line 57, in movie
    response = services.api_request("TMDB", "GET", url, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/app/providers/services.py", line 60, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/app/providers/services.py", line 95, in api_request
    json_response = request_error_handling(error, *args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/app/providers/services.py", line 161, in request_error_handling
    raise error  # re-raise the error if it's not handled
    ^^^^^^^^^^^
  File "/yamtrack/app/providers/services.py", line 90, in api_request
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.themoviedb.org/3/movie/418363?api_key=61572be02f0a068658828f6396aacf60&language=en&append_to_response=recommendations
```

OBS: i have to add the information that i have imported the tv shows and movies from tvtime to simkl when i left tvtime maybe thats why the first entry is from 2017 but i imported last year.

**Comment by FuzzyGrim** [comment]
Hi, I just pushed an update that should fix it.

**Comment by PedroBuffon** [comment]
So the new update to get the app working, the return url is "https://hostname/import/simkl&response_type=code"? i`ve tested without the api keys and i think you left the test one there. when i tried using the id and secret that i`ve created they weren`t being used.

OBS: the new update got all the tv shows/movies correctly plus it gets the animes too.

**Comment by FuzzyGrim** [comment]
Yes, that's right, I'm going to leave the defaults keys as they will only be needed for the import. The code to use personal keys has been added again.

If everything looks good on your end, I will proceed to merge the changes.

**Comment by gnouts** [comment]
It seems I'm getting this error again : 
```
yamtrack-1  | [2025-02-20 23:16:02 +0100] [38] [ERROR] Task Import from SIMKL[xxxx] raised unexpected: KeyError('season/2')
yamtrack-1  | Traceback (most recent call last):
yamtrack-1  |   File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
yamtrack-1  |     R = retval = fun(*args, **kwargs)
yamtrack-1  |                  ^^^^^^^^^^^^^^^^^^^^
yamtrack-1  |   File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
yamtrack-1  |     return self.run(*args, **kwargs)
yamtrack-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack-1  |   File "/yamtrack/integrations/tasks.py", line 44, in import_simkl
yamtrack-1  |     simkl.importer(username, user, mode)
yamtrack-1  |   File "/yamtrack/integrations/imports/simkl.py", line 66, in importer
yamtrack-1  |     process_tv_list(data["shows"], user, bulk_media, warnings)
yamtrack-1  |   File "/yamtrack/integrations/imports/simkl.py", line 129, in process_tv_list
yamtrack-1  |     metadata = app.providers.tmdb.tv_with_seasons(tmdb_id, season_numbers)
yamtrack-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack-1  |   File "/yamtrack/app/providers/tmdb.py", line 124, in tv_with_seasons
yamtrack-1  |     response[f"season/{season_number}"],
yamtrack-1  |     ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack-1  | KeyError: 'season/2'
```
Let me know how I can help you debug that. FTR I have recently mark lots of anime as completed (without ticking episodes) to test https://github.com/FuzzyGrim/Yamtrack/issues/351
