### ISSUE TITLE
Calendar not accessible

### ISSUE THREAD

**Issue by Karsten-Yan** [FuzzyGrim/Yamtrack#292]
Hi,

After updating to the newest version of yamtrack i get an http 500 error when trying to access the calendar.
This is the error from the logs:

```[2024-12-18 08:41:44 +0000] [27] [ERROR] Internal Server Error: /calendar
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/events/views.py", line 14, in calendar
    calendar_events = [
                      ^
  File "/yamtrack/events/views.py", line 18, in <listcomp>
    "color": event.item.event_color,
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/app/models.py", line 177, in event_color
    return colors[self.media_type]
           ~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'book'

```

Thanks in advance for looking into this :)

Best,
Karsten

**Comment by FuzzyGrim** [comment]
Hey, thanks for reporting the issue, I will deploy a release with the fix.
