### ISSUE TITLE
Cannot see season details for some shows

### ISSUE THREAD

**Issue by SirMartin** [FuzzyGrim/Yamtrack#293]
Hi, I made an export tool from Ryot to Yamtrack, using the CSV import format, and it worked fine, but today I found that for some shows (all that I found are Spanish ones, not sure if the language is guilty here)

But when I try to enter a season it crashes.

Here are the details, and it seems fine:

![image](https://github.com/user-attachments/assets/30a2bdc4-d700-46ac-be82-ba283394538f)

But when I click on the season it crashes.

The movie db page is here, because maybe can get some answers: https://www.themoviedb.org/tv/210761-informe

```TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

[2024-12-18 10:55:09 +0000] [21] [ERROR] Internal Server Error: /details/tmdb/tv/210761/informe/season/1

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner

    response = get_response(request)

               ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/http.py", line 64, in inner

    return func(request, *args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/yamtrack/app/views.py", line 122, in season_details

    tv_with_seasons_metadata = services.get_media_metadata(

                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/yamtrack/app/providers/services.py", line 196, in get_media_metadata

    return metadata_retrievers[media_type]()

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/yamtrack/app/providers/services.py", line 187, in <lambda>

    "tv_with_seasons": lambda: tmdb.tv_with_seasons(media_id, season_numbers),

                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/yamtrack/app/providers/tmdb.py", line 123, in tv_with_seasons

    season_data = process_season(

                  ^^^^^^^^^^^^^^^

  File "/yamtrack/app/providers/tmdb.py", line 199, in process_season

    "total_runtime": total_season_runtime(response),

                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/yamtrack/app/providers/tmdb.py", line 262, in total_season_runtime

    sum([episode["runtime"] for episode in response["episodes"]]),

    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

```

Thanks for the help and amazing work!

**Comment by SirMartin** [comment]
I continued trying all my shows and found at least one that was not in Spanish. Also, there are other Spanish shows or non-English shows that work flawlessly.

https://www.themoviedb.org/tv/35338-la-que-se-avecina
https://www.themoviedb.org/tv/237964-muertos-s-l

But for Falling Skies (https://www.themoviedb.org/tv/34967-falling-skies), I am only registered for one season and a couple of episodes for season 1. It fails for all the seasons except for the latest one.

**Comment by FuzzyGrim** [comment]
Hey, thanks for reporting the issue, I will deploy a release with the fix.
